---
routes:

    #########################################################
    # IF / NODES                                            #
    #########################################################

    be_if:
        service:    if
        path:       /api/if
        pattern:    /api/if
        label:      IF
        dscr:       A routegroup, no methods here.


    #########################################################
    # IF SVC / ares_gov_cz / INFO                           #
    #########################################################

    be_if_svc_ares_gov_cz_v1:
        pattern:    ${routes.be_if.path}/svc/ares_gov_cz/docs/v1
        path:       ${routes.be_if.path}/svc/ares_gov_cz/docs/v1
        label:      ares_gov_cz
        dscr:       Caretag SQL based integration service.
        service:    IF
        provides:   docs
        methods:
            get:    Glued\Controllers\IfController:docs_r1

    #########################################################
    # IF / ares_gov_cz / ACT                                #
    #########################################################

    be_if_svc_ares_gov_cz_act_v1:
        pattern:    ${routes.be_if.path}/svc/ares_gov_cz/v1/act/{uuid}/{q}
        path:       ${routes.be_if.path}/svc/ares_gov_cz/v1/act
        label:      Run action
        dscr:       Run an action
        service:    if
        methods:
            get:    Glued\Controllers\IfController:act_r1